from logic_utils import check_guess, parse_guess

# FIX: generated automatically by Claude
def test_winning_guess():
    # If the secret is 50 and guess is 50, it should be a win
    outcome, message = check_guess(50, 50)
    assert outcome == "Win"
    assert message == "🎉 Correct!"

# FIX: generated automatically by Claude
def test_guess_too_high():
    # If secret is 50 and guess is 60, hint should be "Too High"
    outcome, message = check_guess(60, 50)
    assert outcome == "Too High"
    assert message == "📉 Go LOWER!"

# FIX: generated automatically by Claude
def test_guess_too_low():
    # If secret is 50 and guess is 40, hint should be "Too Low"
    outcome, message = check_guess(40, 50)
    assert outcome == "Too Low"
    assert message == "📈 Go HIGHER!"

# FIX: edge case tests for parse_guess generated by Claude for decimal numbers
def test_parse_guess_decimal_rejected():
    # Decimals like "3.7" should be rejected, not silently truncated
    ok, value, err = parse_guess("3.7", low=1, high=20)
    assert ok is False
    assert value is None
    assert err == "Decimals are not allowed. Enter a whole number."

# FIX: edge case tests for parse_guess generated by Claude for negative numbers
def test_parse_guess_negative_number_rejected():
    # Negative numbers are outside any valid game range
    ok, value, err = parse_guess("-5", low=1, high=100)
    assert ok is False
    assert value is None
    assert "Out of range" in err

# FIX: edge case tests for parse_guess generated by Claude for exceeding our range
def test_parse_guess_extremely_large_number_rejected():
    # Huge numbers way beyond the range should be rejected
    ok, value, err = parse_guess("99999999999999", low=1, high=100)
    assert ok is False
    assert value is None
    assert "Out of range" in err
